### ISSUE TITLE
Error when first running

### ISSUE THREAD

**Issue by adoxographer** [Gamevy/pixi-packer#24]
/usr/local/share/npm/lib/node_modules/pixi-packer/node_modules/q/q.js:155
                throw e;
                      ^
TypeError: Object #<Object> has no method 'parse'
    at new Sprite (/usr/local/share/npm/lib/node_modules/pixi-packer/lib/sprite.js:13:22)
    at /usr/local/share/npm/lib/node_modules/pixi-packer/lib/group.js:34:30
    at Array.map (native)
    at /usr/local/share/npm/lib/node_modules/pixi-packer/lib/group.js:33:32
    at _fulfilled (/usr/local/share/npm/lib/node_modules/pixi-packer/node_modules/q/q.js:834:54)
    at self.promiseDispatch.done (/usr/local/share/npm/lib/node_modules/pixi-packer/node_modules/q/q.js:863:30)
    at Promise.promise.promiseDispatch (/usr/local/share/npm/lib/node_modules/pixi-packer/node_modules/q/q.js:796:13)
    at /usr/local/share/npm/lib/node_modules/pixi-packer/node_modules/q/q.js:604:44
    at runSingle (/usr/local/share/npm/lib/node_modules/pixi-packer/node_modules/q/q.js:137:13)
    at flush (/usr/local/share/npm/lib/node_modules/pixi-packer/node_modules/q/q.js:125:13)

**Comment by marekventur** [comment]
Sorry, but to be able to help you I would need some way to reproduce this. Can you upload the images and config you're using?

**Comment by adoxographer** [comment]
Hi!,

Thanks for the quick answer,

Here's the images.js that i'm using and running it on regular pngs.


[images.js.zip](https://github.com/Gamevy/pixi-packer/files/163336/images.js.zip)

**Comment by adoxographer** [comment]
I was also able to replicate by cloning the pixi-packer repo and running:

npm install
pixi-packer ./example.js test-img

**Comment by marekventur** [comment]
Could it be that you're using an outdated version of node? If I remember correctly ```path.parse``` was introduced in a later version of node. Try updating to 4.0 or newer.

**Comment by adoxographer** [comment]
Hi,

the issue was that I was expecting that the npm install took care of all dependencies, but still needed to install imagemagick and graphicsmagick.

all sorted
