### ISSUE TITLE
Error: Stream yields empty buffer

### ISSUE THREAD

**Issue by marekventur** [Gamevy/pixi-packer#5]
```
04:34:17 [04:34:17] 'imagesprites' errored after 1.83 min
04:34:17 [04:34:17] Error: Stream yields empty buffer
04:34:17     at Socket.<anonymous> (/var/lib/jenkins/jobs/the-heist-master/workspace/node_modules/pixi-packer/node_modules/gm/lib/command.js:57:17)
04:34:17     at Socket.emit (events.js:129:20)
04:34:17     at _stream_readable.js:908:16
04:34:17     at process._tickCallback (node.js:355:11)
04:34:17 [04:34:17] 'build' errored after 1.83 min
```

**Comment by marekventur** [comment]
Haven't seen this for a while, closing for now.
